name: CI

on: [push, pull_request]

jobs:
  spelling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check spelling
      uses: crate-ci/typos@master

  pyright:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: console_mod_menu

    - name: Checkout stubs
      uses: actions/checkout@v4
      with:
        repository: bl-sdk/pyunrealsdk
        path: pyunrealsdk
        sparse-checkout: |
          stubs

    - name: Checkout mods_base
      uses: actions/checkout@v4
      with:
        repository: bl-sdk/mods_base
        path: mods_base

    - name: Add stubs to pyproject
      run: >
        sed
        's/# CI ADD STUB PATH HERE/stubPath = "pyunrealsdk\/stubs"\nreportMissingModuleSource = false/'
        console_mod_menu/pyproject.toml
        > pyproject.toml

    - name: Run pyright
      uses: jakebailey/pyright-action@v2
      with:
        extra-args: console_mod_menu

  ruff:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: console_mod_menu

    - name: Checkout mods_base
      uses: actions/checkout@v4
      with:
        repository: bl-sdk/mods_base
        path: mods_base

    - name: Run Ruff Linting
      uses: chartboost/ruff-action@v1
      with:
        args: check console_mod_menu

    - name: Run Ruff Formatting
      uses: chartboost/ruff-action@v1
      with:
        args: format --check console_mod_menu
